# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: true
sudo: required

install:
- R -e 'remotes::install_deps(dep = T)'

script:
- R CMD build .
- R CMD check *tar.gz --as-cran